name: voneo-video-chat
description: A
runtime:
  name: nodejs
  options:
    packagemanager: npm
    typescript: false
    nodeargs: --import tsx
config:
  pulumi:tags:
    value:
      pulumi:template: gcp-typescript
