name: voneo-signalling-api

services:

  signalling-server-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: signalling-server-dev:1.0.0
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: .
          target: /app
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - NODE_ENV=${NODE_ENV}
      - LOCAL=${LOCAL}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - NGROK_HOST=${NGROK_HOST}
    depends_on:
      mysql-db:
        condition: service_healthy

  signalling-server-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: europe-west2-docker.pkg.dev/signalling-api/voneo/voneo-backend:1.0.0
    ports:
      - 3000:3000
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - NODE_ENV=${NODE_ENV}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN}

  mysql-db:
      image: mysql:8.4
      container_name: local-mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_NAME}
      ports:
        - "${DB_PORT:-3306}:3306"
      healthcheck:
        test: ["CMD-SHELL", "mysqladmin ping -h localhost -p${DB_PASSWORD}"]
        interval: 10s
        timeout: 5s
        retries: 5